⏭️ [GitHub] Skipping checks and update for systems called „gateway“

diff --git a/.github/workflows/aws-systems-deploy.yml b/.github/workflows/aws-systems-deploy.yml
--- a/.github/workflows/aws-systems-deploy.yml
+++ b/.github/workflows/aws-systems-deploy.yml
@@ -85,13 +85,17 @@ jobs:
           SYSTEMS='${{ secrets.systems }}'
           for SYSTEM_NAME in ${SYSTEMS//,/ }
           do
-            ECR_REPO=$(echo "${{ inputs.repository }}" | cut -d'-' -f 1 -)-$(echo "$SYSTEM_NAME" | cut -d'-' -f 1)
-            if [[ "$(aws ecr describe-images --registry-id $ACCOUNT_ID --repository-name "$ECR_REPO" --image-ids imageTag="${{ steps.version.outputs.deployment_tag }}" | jq '.imageDetails | length')" == "1" ]]; then
-              echo "🐳  $ECR_REPO:${{ steps.version.outputs.deployment_tag }} exists";
+            if [[ "$SYSTEM_NAME" != *"gateway"* ]]; then
+              ECR_REPO=$(echo "${{ inputs.repository }}" | cut -d'-' -f 1 -)-$(echo "$SYSTEM_NAME" | cut -d'-' -f 1)
+              if [[ "$(aws ecr describe-images --registry-id $ACCOUNT_ID --repository-name "$ECR_REPO" --image-ids imageTag="${{ steps.version.outputs.deployment_tag }}" | jq '.imageDetails | length')" == "1" ]]; then
+                echo "🐳  $ECR_REPO:${{ steps.version.outputs.deployment_tag }} exists";
+              else
+                echo "::error::❌  Docker image for $ECR_REPO:$(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g') not found";
+                exit 1
+              fi
             else
-              echo "::error::❌  Docker image for $ECR_REPO:$(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g') not found";
-              exit 1
-            fi
+              echo "::notice::⏭️  Skipping check for $ECR_REPO:$(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g')"
+            fi 
           done
           echo "::notice::✅  Docker images for all systems are available in version $(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g')"
       -
@@ -109,11 +113,15 @@ jobs:
 
           for SYSTEM_NAME in ${SYSTEMS//,/ }
           do
-            echo "🏷  Set new version for $SYSTEM_NAME in runtime config on AWS Secrets Manager"
-            JQ_PATH=".\"$(echo "$ENV_ID" | tr -cd 0-9a-zA-Z\-)\".\"$(echo "$SYSTEM_NAME" | tr -cd 0-9a-zA-Z\- | cut -d'-' -f 1)\".deploy.version"
-            JQ_COMMAND="$JQ_PATH = \"${{ steps.version.outputs.deployment_tag }}\""
-            AWS_SECRET=$(echo "${AWS_SECRET:-$CURRENT_SECRET}" | (jq . 2> /dev/null || echo "{}") | jq "$JQ_COMMAND")
-            echo "::notice::⬆️ Updated runtime configuration for $SYSTEM_NAME from $(echo $CURRENT_SECRET | jq "$JQ_PATH" | sed 's/./& /g') to version \"$(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g')\""
+            if [[ "$SYSTEM_NAME" != *"gateway"* ]]; then
+              echo "🏷  Set new version for $SYSTEM_NAME in runtime config on AWS Secrets Manager"
+              JQ_PATH=".\"$(echo "$ENV_ID" | tr -cd 0-9a-zA-Z\-)\".\"$(echo "$SYSTEM_NAME" | tr -cd 0-9a-zA-Z\- | cut -d'-' -f 1)\".deploy.version"
+              JQ_COMMAND="$JQ_PATH = \"${{ steps.version.outputs.deployment_tag }}\""
+              AWS_SECRET=$(echo "${AWS_SECRET:-$CURRENT_SECRET}" | (jq . 2> /dev/null || echo "{}") | jq "$JQ_COMMAND")
+              echo "::notice::⬆️ Updated runtime configuration for $SYSTEM_NAME from $(echo $CURRENT_SECRET | jq "$JQ_PATH" | sed 's/./& /g') to version \"$(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g')\""
+            else
+              echo "::notice::⏭️  Skipping version update for $ECR_REPO:$(echo "${{ steps.version.outputs.deployment_tag }}" | sed 's/./& /g')"
+            fi 
           done
           echo "::notice::🔒 Saving new configuration to $SECRET_NAME"
           echo "::debug::$(echo "$AWS_SECRET" | jq .)"
