⏪️ [GitHub] Revert back to GitHub secrets because of know issue in GitHub actions

diff --git a/.github/workflows/aws-systems-restart.yml b/.github/workflows/aws-systems-restart.yml
--- a/.github/workflows/aws-systems-restart.yml
+++ b/.github/workflows/aws-systems-restart.yml
@@ -12,14 +12,6 @@ on:
         description: "Name of application"
         required: true
         type: string
-      systems:
-        description: "Comma separated list of system names of application"
-        required: true
-        type: string
-      environment_identifier:
-        description: "Shortname/identifier of the selected environment"
-        required: true
-        type: string
 
     secrets:
       aws_access_key_id:
@@ -31,6 +23,15 @@ on:
       aws_region:
         description: "AWS Region for Secrets Manager & ASG"
         required: true
+      systems:
+        description: "Comma separated list of system names of application"
+        required: true
+      environment_identifier:
+        description: "Shortname/identifier of the selected environment"
+        required: true
+      environment_aio:
+        description: "Specify if environment is running on AIO instance (string: yes/no)"
+        required: false
 
 jobs:
   Refresh:
@@ -50,11 +51,14 @@ jobs:
         id: refresh
         name: Trigger ASG refresh
         run: |
-          ENV_ID='${{ inputs.environment_identifier }}'
+          ENV_ID='${{ secrets.environment_identifier }}'
           ENV_ID=${ENV_ID:-unknown}
-          if [ "$ENV_ID" = "unknown" ]; then echo "::error::GitHub environment variable ENVIRONMENT_IDENTIFIER is missing"; exit 1; fi
+          if [ "$ENV_ID" = "unknown" ]; then echo "::error::GitHub action input ENVIRONMENT_IDENTIFIER is missing"; exit 1; fi
 
-          SYSTEMS='${{ inputs.systems }}'
+          SYSTEMS='${{ secrets.systems }}'
+          if [ "${{ secrets.environment_aio }}" == "yes" ]; then
+            SYSTEMS=aio
+          fi
 
           echo "### :rocket: ${{ inputs.application }} *$ENV_ID* restart" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
